# Generated by Django 5.1.6 on 2025-05-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
