# Generated by Django 5.1.6 on 2025-05-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_sale_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='unit_price',
            new_name='value',
        ),
    ]
